# Site Settings
title: Start Jekyll
email: phu.dd@samsung.com
description: >
  A guide to getting started with Jekyll.
baseurl: "/startjekyll"
url: "https:jekyllrb.com"
twitter_username: phu.dd
github_username:  phubkhn
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM